template_path: guardduty-master.yaml
stack_name: guardduty-master
dependencies:
  - prod/essentials.yaml
parameters:
  BridgeProdAwsAccountId: !ssm /infra/BridgeProdAwsAccountId
  SynapseProdAwsAccountId: !ssm /infra/SynapseProdAwsAccountId
  LogcentralAwsAccountId: !ssm /infra/LogcentralAwsAccountId
  ScicompAwsAccountId: !ssm /infra/ScicompAwsAccountId
  OperatorEmail: aws.securitycentral@sagebase.org
